modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory 
issueTrackerURL="https://github.com/TelepathicGrunt/RepurposedStructures/issues" #optional
license="https://github.com/TelepathicGrunt/RepurposedStructures/blob/1.16/LICENSE"

[[mods]] #mandatory
modId="repurposed_structures" #mandatory
logoFile="RepurposedStructuresLogo.png"
version="${version}" #mandatory
displayName="Repurposed Structures" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/repurposed-structures"
authors="TelepathicGrunt"
credits="Special thanks to /r/l-ll-ll-l_IsDisLoss, miguelforge, and cannon_foddr for donating some structures to this mod!"
description='''
Taking existing vanilla structures and changing them up for extra variety!
'''

[[dependencies.repurposed_structures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17.0)"